<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pwFeTD.' shared service.

return $this->privates['.service_locator.pwFeTD.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'image' => ['privates', '.errored..service_locator.pwFeTD..App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator.pwFeTD.": it references class "App\\Entity\\Image" but no such service exists.'],
], [
    'image' => 'App\\Entity\\Image',
]);
