<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nzui62o' shared service.

return $this->privates['.service_locator.nzui62o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'order' => ['privates', '.errored..service_locator.nzui62o.App\\Entity\\Orders', NULL, 'Cannot autowire service ".service_locator.nzui62o": it references class "App\\Entity\\Orders" but no such service exists.'],
    'orderDetailRepository' => ['privates', 'App\\Repository\\OrderDetailRepository', 'getOrderDetailRepositoryService.php', true],
], [
    'order' => 'App\\Entity\\Orders',
    'orderDetailRepository' => 'App\\Repository\\OrderDetailRepository',
]);
