<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Yoot9X9' shared service.

return $this->privates['.service_locator.Yoot9X9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'messagesRepository' => ['privates', 'App\\Repository\\Admin\\MessagesRepository', 'getMessagesRepositoryService.php', true],
], [
    'messagesRepository' => 'App\\Repository\\Admin\\MessagesRepository',
]);
