<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QyebdO7' shared service.

return $this->privates['.service_locator.QyebdO7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'orderDetailRepository' => ['privates', 'App\\Repository\\OrderDetailRepository', 'getOrderDetailRepositoryService.php', true],
    'ordersRepository' => ['privates', 'App\\Repository\\OrdersRepository', 'getOrdersRepositoryService.php', true],
], [
    'orderDetailRepository' => 'App\\Repository\\OrderDetailRepository',
    'ordersRepository' => 'App\\Repository\\OrdersRepository',
]);
