<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uTeZyXl' shared service.

return $this->privates['.service_locator.uTeZyXl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepository' => ['privates', 'App\\Repository\\Admin\\CommentRepository', 'getCommentRepositoryService.php', true],
    'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService.php', true],
    'product' => ['privates', '.errored..service_locator.uTeZyXl.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.uTeZyXl": it references class "App\\Entity\\Product" but no such service exists.'],
    'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService.php', true],
    'shopcartRepository' => ['privates', 'App\\Repository\\ShopcartRepository', 'getShopcartRepositoryService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'commentRepository' => 'App\\Repository\\Admin\\CommentRepository',
    'imageRepository' => 'App\\Repository\\ImageRepository',
    'product' => 'App\\Entity\\Product',
    'settingRepository' => 'App\\Repository\\SettingRepository',
    'shopcartRepository' => 'App\\Repository\\ShopcartRepository',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
