<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iePt7HO' shared service.

return $this->privates['.service_locator.iePt7HO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'orderDetailRepository' => ['privates', 'App\\Repository\\OrderDetailRepository', 'getOrderDetailRepositoryService.php', true],
    'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
    'shopcartRepository' => ['privates', 'App\\Repository\\ShopcartRepository', 'getShopcartRepositoryService.php', true],
    'urlGenerator' => ['services', 'router', 'getRouterService', false],
], [
    'mailer' => '?',
    'orderDetailRepository' => 'App\\Repository\\OrderDetailRepository',
    'productRepository' => 'App\\Repository\\ProductRepository',
    'shopcartRepository' => 'App\\Repository\\ShopcartRepository',
    'urlGenerator' => '?',
]);
