<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U9sHqX1' shared service.

return $this->privates['.service_locator.U9sHqX1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'shopcartRepository' => ['privates', 'App\\Repository\\ShopcartRepository', 'getShopcartRepositoryService.php', true],
], [
    'shopcartRepository' => 'App\\Repository\\ShopcartRepository',
]);
