<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iHk0UXp' shared service.

return $this->privates['.service_locator.iHk0UXp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.iHk0UXp.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.iHk0UXp": it references class "App\\Entity\\Event" but no such service exists.'],
], [
    'event' => 'App\\Entity\\Event',
]);
