<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.command.entity_manager_provider' shared service.

include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Tools/Console/EntityManagerProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Orm/ManagerRegistryAwareEntityManagerProvider.php';

return $this->privates['doctrine.orm.command.entity_manager_provider'] = new \Doctrine\Bundle\DoctrineBundle\Orm\ManagerRegistryAwareEntityManagerProvider(($this->services['doctrine'] ?? $this->getDoctrineService()));
