<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.iHk0UXp.App\Entity\Event' shared service.

$this->throw('Cannot autowire service ".service_locator.iHk0UXp": it references class "App\\Entity\\Event" but no such service exists.');
