<?php

namespace App\Controller\Admin;

use App\Entity\Shelf;
use App\Form\ShelfType;
use App\Repository\ShelfRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/shelf")
 */
class ShelfController extends AbstractController
{
    /**
     * @Route("/", name="admin_shelf_index", methods={"GET"})
     */
    public function index(ShelfRepository $shelfRepository): Response
    {
        return $this->render('admin/shelf/index.html.twig', [
            'shelfs' => $shelfRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_shelf_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ShelfRepository $shelfRepository): Response
    {
        $shelf = new Shelf();
        $form = $this->createForm(ShelfType::class, $shelf);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $shelfRepository->add($shelf);
            return $this->redirectToRoute('admin_shelf_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/shelf/new.html.twig', [
            'shelf' => $shelf,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_shelf_show", methods={"GET"})
     */
    public function show(Shelf $shelf): Response
    {
        return $this->render('/admin/shelf/show.html.twig', [
            'shelf' => $shelf,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_shelf_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Shelf $shelf, ShelfRepository $shelfRepository): Response
    {
        $form = $this->createForm(ShelfType::class, $shelf);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $shelfRepository->add($shelf);
            return $this->redirectToRoute('admin_shelf_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/shelf/edit.html.twig', [
            'shelf' => $shelf,
            'form' => $form->createView(),
        ]);
    }

     /**
     * @return string
     */

     private function generateUniqueFileName(){
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="admin_shelf_delete", methods={"POST", "DELETE"})
     */
    public function delete(Request $request, Shelf $shelf, ShelfRepository $shelfRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$shelf->getId(), $request->request->get('_token'))) {
            $shelfRepository->remove($shelf);
        }

        return $this->redirectToRoute('admin_shelf_index', [], Response::HTTP_SEE_OTHER);
    }
}
