<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \App\Entity\Orders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'shipinfo', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'paymentLink', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'paymentId', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'deliveryFees', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'orderDetails'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'shipinfo', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'paymentLink', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'paymentId', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'deliveryFees', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Orders' . "\0" . 'orderDetails'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', []);

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid(?int $userid): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', [$userid]);

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount(?int $amount): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?string $address): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(?string $city): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(?string $phone): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipinfo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipinfo', []);

        return parent::getShipinfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipinfo(?string $shipinfo): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipinfo', [$shipinfo]);

        return parent::setShipinfo($shipinfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote(?string $note): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updated_at): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $created_at): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPaid(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPaid', []);

        return parent::getIsPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPaid(?bool $isPaid): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPaid', [$isPaid]);

        return parent::setIsPaid($isPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentLink', []);

        return parent::getPaymentLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentLink(?string $paymentLink): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentLink', [$paymentLink]);

        return parent::setPaymentLink($paymentLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId(?string $paymentId): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$paymentId]);

        return parent::setPaymentId($paymentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryFees(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryFees', []);

        return parent::getDeliveryFees();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryFees(?int $deliveryFees): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryFees', [$deliveryFees]);

        return parent::setDeliveryFees($deliveryFees);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDetails(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDetails', []);

        return parent::getOrderDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderDetail(\App\Entity\OrderDetail $orderDetail): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderDetail', [$orderDetail]);

        return parent::addOrderDetail($orderDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderDetail(\App\Entity\OrderDetail $orderDetail): \App\Entity\Orders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderDetail', [$orderDetail]);

        return parent::removeOrderDetail($orderDetail);
    }

}
