#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

shopcart_count:
    path: /shopcart/cart/count
    controller: App\Controller\ShopcartController::getCartCount
    methods: GET
