<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Or8mo87' shared service.

return $this->privates['.service_locator.Or8mo87'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService.php', true],
    'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
    'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService.php', true],
    'shopcartRepository' => ['privates', 'App\\Repository\\ShopcartRepository', 'getShopcartRepositoryService.php', true],
], [
    'categoryRepository' => 'App\\Repository\\CategoryRepository',
    'eventRepository' => 'App\\Repository\\EventRepository',
    'paginator' => '?',
    'productRepository' => 'App\\Repository\\ProductRepository',
    'settingRepository' => 'App\\Repository\\SettingRepository',
    'shopcartRepository' => 'App\\Repository\\ShopcartRepository',
]);
