<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yvZURjZ' shared service.

return $this->privates['.service_locator.yvZURjZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'orderDetail' => ['privates', '.errored..service_locator.yvZURjZ.App\\Entity\\OrderDetail', NULL, 'Cannot autowire service ".service_locator.yvZURjZ": it references class "App\\Entity\\OrderDetail" but no such service exists.'],
], [
    'orderDetail' => 'App\\Entity\\OrderDetail',
]);
