<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tNxnSjx' shared service.

return $this->privates['.service_locator.tNxnSjx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService.php', true],
], [
    'mailer' => '?',
    'settingRepository' => 'App\\Repository\\SettingRepository',
]);
