<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ShV_eO7' shared service.

return $this->privates['.service_locator.ShV_eO7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'order' => ['privates', '.errored..service_locator.ShV_eO7.App\\Entity\\Orders', NULL, 'Cannot autowire service ".service_locator.ShV_eO7": it references class "App\\Entity\\Orders" but no such service exists.'],
    'ordersRepository' => ['privates', 'App\\Repository\\OrdersRepository', 'getOrdersRepositoryService.php', true],
], [
    'order' => 'App\\Entity\\Orders',
    'ordersRepository' => 'App\\Repository\\OrdersRepository',
]);
