<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qWt4s.D' shared service.

return $this->privates['.service_locator.qWt4s.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService.php', true],
    'shopcartRepository' => ['privates', 'App\\Repository\\ShopcartRepository', 'getShopcartRepositoryService.php', true],
], [
    'productRepository' => 'App\\Repository\\ProductRepository',
    'shopcartRepository' => 'App\\Repository\\ShopcartRepository',
]);
