<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4KZ7NsJ' shared service.

return $this->privates['.service_locator.4KZ7NsJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.4KZ7NsJ.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.4KZ7NsJ": it references class "App\\Entity\\Event" but no such service exists.'],
    'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true],
], [
    'event' => 'App\\Entity\\Event',
    'eventRepository' => 'App\\Repository\\EventRepository',
]);
