<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ShV_eO7.App\Entity\Orders' shared service.

$this->throw('Cannot autowire service ".service_locator.ShV_eO7": it references class "App\\Entity\\Orders" but no such service exists.');
