<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Doctrine\Bundle\DoctrineBundle\Controller\ProfilerController' shared service.

include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Controller/ProfilerController.php';

return $this->services['Doctrine\\Bundle\\DoctrineBundle\\Controller\\ProfilerController'] = new \Doctrine\Bundle\DoctrineBundle\Controller\ProfilerController(($this->services['twig'] ?? $this->getTwigService()), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['profiler'] ?? $this->getProfilerService()));
