<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.D2s0Hdj.App\Entity\Product' shared service.

$this->throw('Cannot autowire service ".service_locator.D2s0Hdj": it references class "App\\Entity\\Product" but no such service exists.');
