<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRNIKPX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRNIKPX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKRNIKPX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKRNIKPX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKRNIKPX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KRNIKPX',
    'container.build_id' => 'ab4bea9a',
    'container.build_time' => 1726326789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRNIKPX');
