<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUJsXV4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUJsXV4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGUJsXV4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGUJsXV4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGUJsXV4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GUJsXV4',
    'container.build_id' => 'd1a4d238',
    'container.build_time' => 1726677164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUJsXV4');
