<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHYVGma\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHYVGma/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHYVGma.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHYVGma\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXHYVGma\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XHYVGma',
    'container.build_id' => 'a2c3d8d8',
    'container.build_time' => 1726329630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHYVGma');
